### PR TITLE
Remove aggregate endpoint usage

### LINKED ISSUE #99: remove aggregate usage

### PR DESCRIPTION
**Pull request by tcezard**
close #99

### CODE REVIEW

**Comment by lukbut** [comment]
@tcezard Can you please wait until I finish VB5 (end of today) before you merge this, as otherwise I might include this in my comparison?

**Comment by tcezard** [comment]
No intention of merging it until we've release next version.

**Comment by tcezard** [comment]
Validation ID: VB7

**Comment by lukbut** [comment]
To be tested by running `test_recall`

**Pull request merged**
